---
# tasks file for iac-role-odoo-base
- name: Atualizando base APT
  apt:
    update_cache: yes
    state: present

- name: Instalando dependencias do Docker
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  loop:
  - 'sudo'
  - 'apt-transport-https'
  - 'ca-certificates'
  - 'curl'
  - 'software-properties-common'
  - 'python3'
  - 'python3-pip'
  - 'virtualenv'
  - 'python3-setuptools'
  - 'gpg-agent'

- name: Adicionando chave do Docker ao APT
  apt_key:
    id: '0EBFCD88'
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: "Instalando repositório Docker"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_facts['distribution_release']}} stable"
    state: present
    update_cache: yes

- name: Atualizando base APT e instalando docker-ce, docker-compose, containerd.io 
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop:
  - docker-ce
  - docker-ce-cli
  - docker-compose
  - containerd.io
